# Generated by Django 2.2 on 2020-05-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialMedia', '0002_auto_20200525_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='followers',
            field=models.ManyToManyField(related_name='followers', to='socialMedia.Profile'),
        ),
    ]
