# Generated by Django 2.2 on 2020-05-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialMedia', '0004_auto_20200525_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(blank=True, null=True, related_name='follower', to='socialMedia.Profile'),
        ),
    ]
