# Generated by Django 2.2 on 2020-05-26 03:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('socialMedia', '0008_post_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='EveryPostByUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField(blank=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='everyPost', to='socialMedia.Profile')),
            ],
        ),
    ]
