# Generated by Django 2.2 on 2020-05-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialMedia', '0009_everypostbyuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='follower', to='socialMedia.Profile'),
        ),
    ]
