# Generated by Django 2.2 on 2020-05-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialMedia', '0011_auto_20200526_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='number_of_dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='number_of_likes',
            field=models.IntegerField(default=0),
        ),
    ]
