# Generated by Django 2.2 on 2020-05-27 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialMedia', '0013_post_number_of_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='want_to_be_follower',
            field=models.ManyToManyField(blank=True, related_name='wants_to_be_follower', to='socialMedia.Profile'),
        ),
    ]
