# Generated by Django 2.2 on 2020-05-31 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialMedia', '0017_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Name',
        ),
    ]
